services:
  pg_db:
    image: postgres:16.0-alpine
    container_name: pg_db
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  pg_liquid:
    image: liquibase/liquibase
    container_name: pg_liquid
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${PG_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${PG_PASSWORD}
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://pg_db:5432/${PG_DATABASE}
    volumes:
      - ./src/main/resources/db/changelog/:/liquibase/changelog
      - ./src/main/resources/db/db.changelog-master.xml:/liquibase/db.changelog-master.xml
    command: --changelog-file db.changelog-master.xml update

volumes:
  pg-data: