server:
  port: 9013

spring:
  application:
    name: playgrounds-service
  profiles:
    active: LOCAL
  config:
    import: configserver:http://configuration-server:8888/
#      'configuration-server' - is a container name (see more about Docker's networks DNS...)


